/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpat2021;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sims <your.name at your.org>
 */
public class JoinStokvelGUI extends javax.swing.JFrame {

    /**
     * Creates new form JoinStokvelGUI
     */
    
    Tools t = new Tools();
    
    public JoinStokvelGUI() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        lblCellNo = new javax.swing.JLabel();
        lblStokvel = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        cmbBank = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        cmbStokvel = new javax.swing.JComboBox<>();
        btnStokvelInfo = new javax.swing.JButton();
        txfEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        pwfPassword = new javax.swing.JPasswordField();
        pwfConfirmPassword = new javax.swing.JPasswordField();
        ftxfDOB = new javax.swing.JFormattedTextField();
        ftxfCellNo = new javax.swing.JFormattedTextField();
        btnJoin = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Join Stokvel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 43, -1, -1));

        lblSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblSurname.setText("Surname:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 86, -1, -1));

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(240, 240, 240));
        lblDOB.setText("Date of Birth:");
        getContentPane().add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 129, -1, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(240, 240, 240));
        lblGender.setText("Gender:");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 38, -1, -1));

        lblBank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBank.setForeground(new java.awt.Color(240, 240, 240));
        lblBank.setText("Bank:");
        getContentPane().add(lblBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 84, -1, -1));

        lblCellNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCellNo.setForeground(new java.awt.Color(240, 240, 240));
        lblCellNo.setText("Cell No:");
        getContentPane().add(lblCellNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 129, -1, -1));

        lblStokvel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStokvel.setForeground(new java.awt.Color(240, 240, 240));
        lblStokvel.setText("Stokvel:");
        getContentPane().add(lblStokvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 179, -1, -1));

        txfName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNameActionPerformed(evt);
            }
        });
        getContentPane().add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 44, 85, -1));

        txfSurname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txfSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 87, 85, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        cmbGender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 37, 100, -1));

        cmbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Absa", "Standard Bank", "FNB", "Investec", "Capitec", "Nedbank", "Discovery Bank", "TymeBank", "African Bank" }));
        cmbBank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 83, -1, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(240, 240, 240));
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(240, 240, 240));
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(240, 240, 240));
        lblConfirmPassword.setText("Confirm Password:");
        getContentPane().add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        cmbStokvel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emalangeni", "Blossom", "Dynamite", "Imvelo", "Eclipse", "Inyoni", "Abantu", "Volcano", "Fusion", "Golden" }));
        cmbStokvel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbStokvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 178, 85, -1));

        btnStokvelInfo.setText("Stokvel Info");
        btnStokvelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStokvelInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokvelInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnStokvelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 178, 91, 22));

        txfEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, -1));

        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 329, 40, -1));

        pwfPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, -1));

        pwfConfirmPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pwfConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 80, -1));

        ftxfDOB.setColumns(10);
        try {
            ftxfDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftxfDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 129, -1, -1));

        try {
            ftxfCellNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftxfCellNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 129, 100, -1));

        btnJoin.setText("Join");
        btnJoin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        getContentPane().add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 315, 60, 33));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\myboy\\Downloads\\Black dots.jpg")); // NOI18N
        Background.setText("jLabel1");
        Background.setMaximumSize(new java.awt.Dimension(500, 500));
        Background.setMinimumSize(new java.awt.Dimension(500, 500));
        Background.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStokvelInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokvelInfoActionPerformed

        try {
            JOptionPane.showMessageDialog(null, t.getStokvelInfo("") , "STOKVEL INFO", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(JoinStokvelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStokvelInfoActionPerformed

    private void txfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void cmbBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBankActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LoginGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
     //Checks if all fields are correct and relevant then creates new StokvelMember and adds them to array and database through addStokvelMember() method. If any data is wrongly inputted, an error message will be shown
        if (txfName.getText().length() > 0 && txfSurname.getText().length() > 0 && ftxfDOB.getText().length() == 10 && ftxfCellNo.getText().length() == 10 && txfEmail.getText().length() > 0 && pwfPassword.getSelectedText().length() > 0 && pwfConfirmPassword.getSelectedText().length() > 0) 
        { 
            if (Tools.checkAge(ftxfDOB.getSelectedText()) == true) 
            {
                if (pwfPassword.getSelectedText().length() >= 5) 
                {
                    if (pwfPassword.getSelectedText().compareTo(pwfConfirmPassword.getSelectedText()) == 0) 
                    {
                        try {
                            if (t.checkEmail(txfEmail.getText()) == true)
                            {
                              StokvelMemberManager ssm = new StokvelMemberManager(); 
                              ssm.addStokvelMember(txfEmail.getText(),pwfPassword.getSelectedText() , txfName.getText(), txfSurname.getText(), ftxfDOB.getSelectedText(), cmbGender.getSelectedItem().toString(), cmbBank.getSelectedItem().toString(), ftxfCellNo.getSelectedText(), cmbStokvel.getSelectedItem().toString());
                              
                              StokvelMember NewUser = ssm.getDetails(txfEmail.getText());
                              new HomeGUI(NewUser).setVisible(true);
                              this.dispose();
                            }
                            else
                            {
                              JOptionPane.showMessageDialog(null, "Account with email already exists", "", JOptionPane.INFORMATION_MESSAGE);  
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(JoinStokvelGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Passwords do not match", "", JOptionPane.INFORMATION_MESSAGE);
                    }
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Password must contain at least 5 characters", "", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            else 
            {
              JOptionPane.showMessageDialog(null, "Users must be 16 or older", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        else
       {
            JOptionPane.showMessageDialog(null, "A field has been left empty\n\nNote: Cellphone number must have 10 digits", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinStokvelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinStokvelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinStokvelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinStokvelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinStokvelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnStokvelInfo;
    private javax.swing.JComboBox<String> cmbBank;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbStokvel;
    private javax.swing.JFormattedTextField ftxfCellNo;
    private javax.swing.JFormattedTextField ftxfDOB;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblCellNo;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStokvel;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JPasswordField pwfConfirmPassword;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}
