/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpat2021;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sims <your.name at your.org>
 */
public class ManageAccountGUI extends javax.swing.JFrame {

    /**
     * Creates new form FinancesGUI
     */
    
    public static StokvelMember User;
    public DB db;
    
    public ManageAccountGUI(StokvelMember sm) throws SQLException 
    {
        initComponents();
        User = sm;
        Tools t = new Tools();
        String info = t.getStokvelInfo(User.getStokvel());
        txaInfo.setText(info + User.getPayments());//also displays the users total payments made
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPay = new javax.swing.JButton();
        btnChangeBank = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInfo = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnChangeStokvel = new javax.swing.JButton();
        cmbBank = new javax.swing.JComboBox<>();
        cmbStokvel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Account");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 49, 70, 40));

        btnChangeBank.setText("Change Bank");
        btnChangeBank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangeBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBankActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 159, 95, 27));

        txaInfo.setColumns(20);
        txaInfo.setRows(5);
        jScrollPane1.setViewportView(txaInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 11, 215, 110));

        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 270, 45, -1));

        btnHelp.setText("Help");
        btnHelp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 40, -1));

        btnChangeStokvel.setText("Change Stokvel");
        btnChangeStokvel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangeStokvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStokvelActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeStokvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 159, 107, 27));

        cmbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Absa", "Standard Bank", "FNB", "Investec", "Capitec", "Nedbank", "Discovery Bank", "TymeBank", "African Bank" }));
        cmbBank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 204, 95, 28));

        cmbStokvel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emalangeni", "Blossom", "Dynamite", "Imvelo", "Eclipse", "Inyoni", "Abantu", "Volcano", "Fusion", "Golden" }));
        cmbStokvel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbStokvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 204, 107, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\myboy\\Downloads\\Black sand wave.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBankActionPerformed
       int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to change your Bank?", "", JOptionPane.YES_NO_OPTION);
       
        if (option == 0) 
        {
           try {
               StokvelMemberManager  ssm = new StokvelMemberManager();
               ssm.changeBank(User.getEmail(), cmbBank.getSelectedItem().toString());
               JOptionPane.showMessageDialog(null,"Sucessfully changed bank", "", JOptionPane.INFORMATION_MESSAGE);
           } catch (SQLException ex) {
               Logger.getLogger(ManageAccountGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnChangeBankActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new HomeGUI(User).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        new HelpGUI(User).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnChangeStokvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStokvelActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to change your Stokvel?", "", JOptionPane.YES_NO_OPTION);
       
        if (option == 0) 
        {
           try {
               StokvelMemberManager  ssm = new StokvelMemberManager();
               ssm.changeBank(User.getEmail(), cmbStokvel.getSelectedItem().toString());
               JOptionPane.showMessageDialog(null,"Sucessfully changed stokvel", "", JOptionPane.INFORMATION_MESSAGE);
           } catch (SQLException ex) {
               Logger.getLogger(ManageAccountGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnChangeStokvelActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to make your monthly payment now?", "", JOptionPane.YES_NO_OPTION);
       
        if (option == 0) 
        {
           try {
               StokvelMemberManager  ssm = new StokvelMemberManager();
               ssm.addPayments(User.getEmail(), User.getStokvel());
               JOptionPane.showMessageDialog(null,"Sucessfully changed bank", "", JOptionPane.INFORMATION_MESSAGE);
               db.query("INSERT INTO tblTransactions (Email, Stokvel, TransactionDate, TransactionAmount) VALUES('" + User.getEmail() + "', '" +  User.getStokvel()+ "', #" + Tools.getDate() + "#, "  + ssm.getPayments(User.getStokvel()) + ")" ); //adds transaction to the database
           } catch (SQLException ex) {
               Logger.getLogger(ManageAccountGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void cmbBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageAccountGUI(User).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageAccountGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeBank;
    private javax.swing.JButton btnChangeStokvel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cmbBank;
    private javax.swing.JComboBox<String> cmbStokvel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaInfo;
    // End of variables declaration//GEN-END:variables
}
